version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile # Usamos el Dockerfile para el entorno de desarrollo del frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app # Sincroniza los archivos del frontend con el contenedor
    ports:
      - 3000:3000 # Exponemos el puerto 3000 para el frontend
    depends_on:
      - backend # Aseguramos que el backend esté listo antes de levantar el frontend

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile # Usamos el Dockerfile para el entorno de desarrollo del backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/app # Sincroniza los archivos del backend con el contenedor
    ports:
      - 5000:5000 # Exponemos el puerto 5000 para la API del backend
    environment:
      - NODE_ENV=development # Configuramos el entorno como desarrollo
    depends_on:
      - mongo # El backend depende de MongoDB

  nginx:
    image: nginx:1.20.1
    container_name: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro # Montamos la configuración de Nginx
    ports:
      - 80:80 # Exponemos el puerto 80 para acceder a la aplicación
    depends_on:
      - frontend
      - backend # Nginx depende del frontend y backend

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db # Volumen para la persistencia de los datos de MongoDB
    networks:
      - app-network

volumes:
  mongo_data: # Volumen para MongoDB

networks:
  app-network:
    driver: bridge
