version: "3"
services:
  todo-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=your_mongo_url
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  redis_data:
  mongo_data:
